#!/usr/bin/python3

#20260915 AI generation
#need lib exdxf install: pip install ezdxf
#grbl
#convert 2d Freecad dxf file to gcode 2d
#no cuttong order from inside to outside, need to create multiple path for inside and edge
import ezdxf,sys
from ezdxf import path


def convert_dxf_to_gcode(
    dxf_path, gcode_path, feed_rate=500, safe_z=5.0, cut_z=-1.0, tolerance=0.01
):
  """Reads a DXF file and writes out a clean G-code program."""
  try:
    doc = ezdxf.readfile(dxf_path)
  except IOError:
    print(f"Error: Could not open {dxf_path}")
    return
  except ezdxf.DXFStructureError:
    print("Error: Invalid or corrupted DXF file.")
    return

  msp = doc.modelspace()
  gcode = [
      "; Generated by Python DXF-to-Gcode Converter",
      "G21",  # Millimeters (use G20 for inches)
      "G90",  # Absolute positioning
      "G17",  # plan xy
      #f"G0 Z{safe_z}",  # Move to safe height
  ]

  for entity in msp:
    try:
      # Convert any vector entity into a geometric path and flatten it
      geom_path = path.make_path(entity)
      vertices = list(geom_path.flattening(tolerance))

      if not vertices:
        continue

      # Rapid move to start point, plunge, then cut linear segments
      start = vertices[0]
      gcode.append("M5") #turn off laser
      gcode.append("; start new entity =========================")
      gcode.append(f"G0 X{start.x:.4f} Y{start.y:.4f}")
      #gcode.append(f"G1 Z{cut_z} F{feed_rate}")
      gcode.append("M3 S100")
      gcode.append("G1 F1")
      gcode.append("G4 P1") #piercing 1s
      gcode.append(f"G1 F{feed_rate}")


      for v in vertices[1:]:
        gcode.append(f"G1 X{v.x:.4f} Y{v.y:.4f}")

      # Retract tool after each entity path
      #gcode.append(f"G0 Z{safe_z}")

    except (AttributeError, TypeError):
      # Skip entities that cannot be converted to paths (e.g., TEXT, DIMENSION)
      continue

  # Program Footer
  #gcode.append(f"G0 Z{safe_z}")
  gcode.append("M5")   # Laser off
  gcode.append("G0 X0 Y0")
  gcode.append("M30")  # End of program

  with open(gcode_path, "w") as f:
    f.write("\n".join(gcode))
  print(f"G-code successfully saved to: {gcode_path}")


if __name__ == "__main__":
  convert_dxf_to_gcode(sys.argv[1],sys.argv[2])
